proxies:
###############ã€é”šç‚¹ã€‘###############
provider: &PROVIDER { type: http, interval: 3600, health-check: { enable: true, url: 'http://www.gstatic.com/generate_204', interval: 600 } }
rule: &RULE { type: http, behavior: classical, interval: 86400 }
select: &SELECT { type: select }
fallback: &FALLBACK { type: fallback, url: 'http://www.gstatic.com/generate_204', interval: 300 }
url-test: &URL-TEST { type: url-test, url: 'http://www.gstatic.com/generate_204', interval: 300 }
## 1 ## è¯·æ ¹æ®èŠ‚ç‚¹åç§°åŒæ—¶å–æ¶ˆæ³¨é‡Š(1-4)## 1 ## 
NODES: &NODES
  proxies:
    - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
    - ğŸŒ€ æ‰‹åŠ¨åˆ‡æ¢
    # - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
    # - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹
    # - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
    # - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
    # - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
    # - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
    - ğŸ”„ å»¶è¿Ÿæœ€ä½
    - ğŸ¯ å…¨çƒç›´è¿
## 2 ## è¯·æ ¹æ®èŠ‚ç‚¹åç§°åŒæ—¶å–æ¶ˆæ³¨é‡Š(1-4)## 2 ## 
NODES2: &NODES2
  proxies:
    - ğŸ”„ å»¶è¿Ÿæœ€ä½
    - ğŸŒ€ æ‰‹åŠ¨åˆ‡æ¢
    # - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
    # - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹
    # - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
    # - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
    # - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
    # - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
    - ğŸ¯ å…¨çƒç›´è¿
proxy-providers:
  AllProxy: &AllProxy { <<: *PROVIDER, path: ./Provider/Proxy/AllProxy.yaml, url: "http://127.0.0.1:25500/getprofile?name=profiles/formyairport.ini&token=password&list=true" }
## 3 ## è¯·æ ¹æ®èŠ‚ç‚¹åç§°åŒæ—¶å–æ¶ˆæ³¨é‡Š(1-4)## 3 ## 
  # HK: { <<: *AllProxy, filter: "ğŸ‡­ğŸ‡°|æ¸¯|è™šé€š|(?i)HK|Hong" }
  # SG: { <<: *AllProxy, filter: "(?i)ğŸ‡¸ğŸ‡¬|æ–°åŠ å¡|ç‹®|SG|Singapore" }
  # TW: { <<: *AllProxy, filter: "(?i)TW|å°|Tai" }
  # JP: { <<: *AllProxy, filter: "(?i)ğŸ‡¯ğŸ‡µ|æ—¥|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|JP|Japan" }
  # US: { <<: *AllProxy, filter: "(?i)ğŸ‡ºğŸ‡¸|ç¾|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|US|United States" }
  # KR: { <<: *AllProxy, filter: "(?i)ğŸ‡°ğŸ‡·|éŸ©|éŸ“|é¦–å°”|KR|Korea" }

proxy-groups:
  - { name: 'ğŸš€ èŠ‚ç‚¹é€‰æ‹©', <<: [*SELECT, *NODES2] }
  - { name: 'ğŸŒ€ æ‰‹åŠ¨åˆ‡æ¢', <<: *SELECT, use: [AllProxy] }
  - { name: 'ğŸ“² Telegram', <<: [*SELECT, *NODES] }
  - { name: 'ğŸ“¹ Youtube', <<: [*SELECT, *NODES] }
  - { name: 'ğŸ¥ Netflix', <<: [*SELECT, *NODES] }
  - { name: 'ğŸ“ˆ SpeedTest', <<: [*SELECT, *NODES] }
  - { name: 'ğŸŒ å›½å¤–åª’ä½“', <<: [*SELECT, *NODES] }
  - { name: 'ğŸ’° PayPal', <<: [*SELECT, *NODES] }
  - { name: 'ğŸ è‹¹æœæœåŠ¡', <<: [*SELECT, *NODES] }
  - { name: 'â“‚ï¸ OneDrive', <<: [*SELECT, *NODES] }
  - { name: 'â“‚ï¸ å¾®è½¯æœåŠ¡', <<: [*SELECT, *NODES] }
  - { name: 'ğŸ® æ¸¸æˆæœåŠ¡', <<: [*SELECT, *NODES] }
  - { name: 'ğŸŸ æ¼ç½‘ä¹‹é±¼', <<: [*SELECT, *NODES] }
## 4 ## è¯·æ ¹æ®èŠ‚ç‚¹åç§°åŒæ—¶å–æ¶ˆæ³¨é‡Š(1-4)## 4 ## 
  # - { name: 'ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹', <<: *URL-TEST, use: [HK] }
  # - { name: 'ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹', <<: *URL-TEST, use: [SG] }
  # - { name: 'ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹', <<: *URL-TEST, use: [TW] }
  # - { name: 'ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹', <<: *URL-TEST, use: [JP] }
  # - { name: 'ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹', <<: *URL-TEST, use: [US] }
  # - { name: 'ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹', <<: *URL-TEST, use: [KR] }
  - { name: 'ğŸ”„ å»¶è¿Ÿæœ€ä½', <<: *URL-TEST, use: [AllProxy] }
  - { name: 'ğŸ¯ å…¨çƒç›´è¿', <<: *SELECT, proxies: [DIRECT] }

rule-providers:
  Lan: { <<: *RULE, path: ./Provider/RuleSet/Lan.yaml, url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Lan/Lan.yaml } #æœ¬åœ°å±€åŸŸç½‘åœ°å€
  PrivateTracker: { <<: *RULE, path: ./Provider/RuleSet/PrivateTracker.yaml, url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/PrivateTracker/PrivateTracker.yaml } # PTä¸‹è½½
  CloudCN: { <<: *RULE, path: ./Provider/RuleSet/CloudCN.yaml, url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Cloud/CloudCN/CloudCN.yaml } # å›½å†…äº‘è®¡ç®—
  ChinaMax: { <<: *RULE, path: ./Provider/RuleSet/ChinaMax.yaml, url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/ChinaMax/ChinaMax_Classical.yaml } # å›½å†…ç½‘ç«™/IPåˆé›†
  NTPService: { <<: *RULE, path: ./Provider/RuleSet/NTPService.yaml, url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/NTPService/NTPService.yaml }
  PayPal: { <<: *RULE, path: ./Provider/RuleSet/PayPal.yaml, url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/PayPal/PayPal.yaml }
  OneDrive: { <<: *RULE, path: ./Provider/RuleSet/OneDrive.yaml, url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/OneDrive/OneDrive.yaml }
  Microsoft: { <<: *RULE, path: ./Provider/RuleSet/Microsoft.yaml, url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Microsoft/Microsoft.yaml }
  Apple: { <<: *RULE, path: ./Provider/RuleSet/Apple.yaml, url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Apple/Apple.yaml }
  Telegram: { <<: *RULE, path: ./Provider/RuleSet/Telegram.yaml, url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Telegram/Telegram.yaml }
  Game: { <<: *RULE, path: ./Provider/RuleSet/Game.yaml, url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Game/Game.yaml }
  PROXY: { <<: *RULE, path: ./Provider/RuleSet/PROXY.yaml, url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Proxy/Proxy_Classical.yaml }
  YouTube: { <<: *RULE, path: ./Provider/RuleSet/YouTube.yaml, url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/YouTube/YouTube.yaml }
  Netflix: { <<: *RULE, path: ./Provider/RuleSet/Netflix.yaml, url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Netflix/Netflix.yaml }
  GlobalMedia: { <<: *RULE, path: ./Provider/RuleSet/GlobalMedia.yaml, url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/GlobalMedia/GlobalMedia_Classical.yaml }
  Speedtest: { <<: *RULE, path: ./Provider/RuleSet/Speedtest.yaml, url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Speedtest/Speedtest.yaml }

rules:
  - RULE-SET,Lan,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,NTPService,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,PrivateTracker,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,CloudCN,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,Telegram,ğŸ“² Telegram
  - RULE-SET,YouTube,ğŸ“¹ Youtube
  - RULE-SET,Netflix,ğŸ¥ Netflix
  - RULE-SET,Speedtest,ğŸ“ˆ SpeedTest
  - RULE-SET,GlobalMedia,ğŸŒ å›½å¤–åª’ä½“
  - RULE-SET,PayPal,ğŸ’° PayPal
  - RULE-SET,Apple,ğŸ è‹¹æœæœåŠ¡
  - RULE-SET,OneDrive,â“‚ï¸ OneDrive
  - RULE-SET,Microsoft,â“‚ï¸ å¾®è½¯æœåŠ¡
  - RULE-SET,Game,ğŸ® æ¸¸æˆæœåŠ¡
  - RULE-SET,PROXY,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - RULE-SET,ChinaMax,ğŸ¯ å…¨çƒç›´è¿
  - GEOIP,CN,ğŸ¯ å…¨çƒç›´è¿
  - MATCH,ğŸŸ æ¼ç½‘ä¹‹é±¼
